/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#0e0e13",
        "secondary-fixed": "#e9ddff",
        "on-secondary": "#3c0090",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#1b1b20",
        "on-background": "#e4e1e9",
        "outline": "#859398",
        "inverse-primary": "#00687b",
        "on-primary-fixed-variant": "#004e5d",
        "primary-fixed-dim": "#00d9ff",
        "on-tertiary": "#00391d",
        "background": "#131318",
        "surface": "#131318",
        "tertiary": "#58ffa1",
        "on-tertiary-fixed": "#00210e",
        "inverse-on-surface": "#303036",
        "surface-dim": "#131318",
        "on-tertiary-container": "#005f34",
        "surface-container-high": "#2a292f",
        "on-surface": "#e4e1e9",
        "on-primary-fixed": "#001f26",
        "outline-variant": "#3c494d",
        "surface-container": "#1f1f25",
        "on-secondary-container": "#ddcdff",
        "primary": "#afecff",
        "surface-container-highest": "#35343a",
        "surface-bright": "#39383e",
        "primary-fixed": "#aeecff",
        "secondary-container": "#7000ff",
        "tertiary-fixed-dim": "#00e383",
        "on-tertiary-fixed-variant": "#00522c",
        "on-primary": "#003641",
        "inverse-surface": "#e4e1e9",
        "surface-tint": "#00d9ff",
        "on-error": "#690005",
        "surface-variant": "#35343a",
        "tertiary-fixed": "#5bffa1",
        "error-container": "#93000a",
        "secondary": "#d1bcff",
        "on-primary-container": "#005b6c",
        "tertiary-container": "#00e383",
        "error": "#ffb4ab",
        "on-surface-variant": "#bbc9ce",
        "secondary-fixed-dim": "#d1bcff",
        "primary-container": "#00d9ff",
        "on-secondary-fixed": "#23005b",
        "on-secondary-fixed-variant": "#5700c9"
      },
      spacing: {
        "2xl": "3rem",
        "gutter": "16px",
        "base": "4px",
        "sm": "0.5rem",
        "xl": "2rem",
        "xs": "0.25rem",
        "md": "1rem",
        "lg": "1.5rem",
        "container-margin": "24px"
      },
      fontFamily: {
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-code": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-code": ["13px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "1.4", fontWeight: "500" }],
      }
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
